# Production Database Configuration (PostgreSQL)

# Spring Boot automatically substitutes values from the environment,
# and if there are none (for example, when running locally), it will take the value after the colon.
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:library_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
# On production, ONLY Liquibase changes the DB schema. validate ensures that entities match tables.
spring.jpa.hibernate.ddl-auto=validate

# Server & Security Settings

# Port 8080 is optimal. Nginx is usually installed in front of the application on the live server (443 -> 8080)
server.port=8080

# Disable Open Session in View to save connection pool on production
spring.jpa.open-in-view=false

# Limiting the output of Actuator metrics for security
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

# Hide detailed error traces from application clients
app.errors.show-details=false

# Liquibase Production Integration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
# Liquibase will only execute changesets where context is not specified or equal to "prod"
spring.liquibase.contexts=prod

# JWT Security Settings
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION:36000000}