# =========================================================================
# CORE APPLICATION SETTINGS
# =========================================================================
# Common Application Settings
spring.application.name=LibraryManagementSystem

# Set Default Active Profile (Change to 'prod' when deploying)
#spring.profiles.active=dev
spring.profiles.active=@activatedProperties@
# spring.profiles.include=${spring.profiles.active}

# =========================================================================
# DATABASE & MIGRATION SETTINGS (GLOBAL)
# =========================================================================
# Master-file path
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

# Active Profile Spring (for example, dev or prod) in the context of Liquibase
spring.liquibase.contexts=${spring.profiles.active}

# Force Hibernate Schema Validation to occur AFTER Liquibase bean setup is fully completed
spring.jpa.query.fail-on-pagination-over-collection-fetch=true

# =========================================================================
# GLOBAL CACHE SETTINGS
# =========================================================================
spring.cache.cache-names=popularIsbns
app.cache.ttl-minutes=10

# =========================================================================
# GLOBAL MAIL SETTINGS
# =========================================================================
# Common Mail Configuration
spring.mail.default-encoding=UTF-8

# =========================================================================
# LOGGING SYSTEM CONFIGURATION
# =========================================================================
# Operational runtime engine logging levels
logging.level.liquibase=INFO
logging.level.org.liquibase.database=INFO

# =========================================================================
# API DOCUMENTATION SETTINGS
# =========================================================================
# Swagger will ONLY document classes from the API package
springdoc.packages-to-scan=com.kvl.library.controller.api

# =========================================================================
# INTERNATIONALIZATION (I18N) SETTINGS
# =========================================================================
# Basename path for message resource bundles inside resources/i18n/
spring.messages.basename=i18n/messages

# Enforce UTF-8 encoding for proper Cyrillic character rendering
spring.messages.encoding=UTF-8