# Point PostgreSQL dialect for Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

# Switch on Liquibase to use SQL-migration files to containers
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
spring.liquibase.contexts=test

# Switch off the default transactions in OSIV for test predictivity
spring.jpa.open-in-view=false

# Limit Hikari pool for test environment
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=20000